'use strict';

export default {
  dotBG: '#534940',
  textFG: '#EFECE7',
  poiFG: '#333',
  poiBG: '#d15b06',
  subtitleFG: '#dedbd6',
  yearFG: '#a39d93',
  lineFG: '#a39d93',
  width: window.innerWidth,
  height: window.innerHeight,
  itemHeight: 22,
  poiHeight: 120,
  itemHeightBottom: 36,
  hStep: 5,
  mainBG: '#242424',
  itemZoom: 1.3,
  itemAlpha: 0.7,
  textFont: '9pt Ubuntu, Sans',
  subtitleFont: '8pt Ubuntu, Sans',
  iconFont: '18pt FontAwesome',
  nameFont: 'bold 15pt Ubuntu, Sans',
  summaryFont: '10pt Ubuntu, Sans',
};
